/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.LayoutStyle;

/**
 *
 * @author Rain
 */
public class vistaBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form vistaBienvenida
     */
    public vistaBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        repcompbtn = new JButton();
        repcelbtn = new JButton();
        reptvbtn = new JButton();
        cerrarbtn = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //---- repcompbtn ----
        repcompbtn.setText("Reparacion de Computador");

        //---- repcelbtn ----
        repcelbtn.setText("Reparacion de Celular");

        //---- reptvbtn ----
        reptvbtn.setText("Reparacion de Televisor");

        //---- cerrarbtn ----
        cerrarbtn.setText("Cerrar");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(repcelbtn)
                            .addGap(137, 137, 137)
                            .addComponent(repcompbtn))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGap(162, 162, 162)
                                    .addComponent(reptvbtn))
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(cerrarbtn)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(repcelbtn)
                        .addComponent(repcompbtn))
                    .addGap(44, 44, 44)
                    .addComponent(reptvbtn)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                    .addComponent(cerrarbtn)
                    .addGap(27, 27, 27))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaBienvenida().setVisible(true);
            }
        });

    }

    public vistaBienvenida(JButton cerrarbtn, JButton repcelbtn, JButton repcompbtn, JButton reptvbtn) {
        this.cerrarbtn = cerrarbtn;
        this.repcelbtn = repcelbtn;
        this.repcompbtn = repcompbtn;
        this.reptvbtn = reptvbtn;
    }

    

    public JButton getCerrarbtn() {
        return cerrarbtn;
    }

    public void setCerrarbtn(JButton cerrarbtn) {
        this.cerrarbtn = cerrarbtn;
    }

    public JButton getRepcelbtn() {
        return repcelbtn;
    }

    public void setRepcelbtn(JButton repcelbtn) {
        this.repcelbtn = repcelbtn;
    }

    public JButton getRepcompbtn() {
        return repcompbtn;
    }

    public void setRepcompbtn(JButton repcompbtn) {
        this.repcompbtn = repcompbtn;
    }

    public JButton getReptvbtn() {
        return reptvbtn;
    }

    public void setReptvbtn(JButton reptvbtn) {
        this.reptvbtn = reptvbtn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JButton repcompbtn;
    private JButton repcelbtn;
    private JButton reptvbtn;
    private JButton cerrarbtn;
    // End of variables declaration//GEN-END:variables
}
