/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author Rain
 */
public class vistaComputadores extends javax.swing.JFrame {

    /**
     * Creates new form vistaComputadores
     */
    public vistaComputadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jLabel4 = new JLabel();
        discopctxt = new JTextField();
        totalpctxt = new JTextField();
        jLabel5 = new JLabel();
        regresarbtn = new JButton();
        cerrarbtn = new JButton();
        reparacionpbtn = new JButton();
        modelpctxt = new JTextField();
        procesadorpctxt = new JTextField();
        reparacioncbtn = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        marcapctxt = new JTextField();
        jLabel8 = new JLabel();
        jLabel3 = new JLabel();
        rampctxt = new JTextField();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //---- jLabel4 ----
        jLabel4.setText("Marca");

        //---- discopctxt ----
        discopctxt.addActionListener(e -> discopctxtActionPerformed(e));

        //---- totalpctxt ----
        totalpctxt.addActionListener(e -> totalpctxtActionPerformed(e));

        //---- jLabel5 ----
        jLabel5.setText("Disco");

        //---- regresarbtn ----
        regresarbtn.setText("Regresar");

        //---- cerrarbtn ----
        cerrarbtn.setText("Cerrar");

        //---- reparacionpbtn ----
        reparacionpbtn.setText("Reparacion Preventiva");
        reparacionpbtn.addActionListener(e -> reparacionpbtnActionPerformed(e));

        //---- modelpctxt ----
        modelpctxt.addActionListener(e -> modelpctxtActionPerformed(e));

        //---- procesadorpctxt ----
        procesadorpctxt.addActionListener(e -> procesadorpctxtActionPerformed(e));

        //---- reparacioncbtn ----
        reparacioncbtn.setText("Reparacion Correctiva");

        //---- jLabel1 ----
        jLabel1.setText("Modelo");

        //---- jLabel2 ----
        jLabel2.setText("RAM");

        //---- marcapctxt ----
        marcapctxt.addActionListener(e -> marcapctxtActionPerformed(e));

        //---- jLabel8 ----
        jLabel8.setText("Total");

        //---- jLabel3 ----
        jLabel3.setText("Procesador");

        //---- rampctxt ----
        rampctxt.addActionListener(e -> rampctxtActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(reparacioncbtn)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reparacionpbtn))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGap(98, 98, 98)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(marcapctxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addComponent(modelpctxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addComponent(procesadorpctxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addComponent(rampctxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addComponent(discopctxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(64, 64, 64))
                                .addComponent(totalpctxt, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(regresarbtn)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cerrarbtn)))
                    .addGap(30, 30, 30))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel4))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(marcapctxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(modelpctxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(rampctxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(discopctxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(procesadorpctxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(10, 10, 10)
                            .addComponent(totalpctxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGap(12, 12, 12)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(reparacioncbtn)
                        .addComponent(reparacionpbtn))
                    .addGap(29, 29, 29)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(cerrarbtn)
                        .addComponent(regresarbtn))
                    .addGap(27, 27, 27))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void discopctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discopctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discopctxtActionPerformed

    private void totalpctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpctxtActionPerformed

    private void reparacionpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparacionpbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reparacionpbtnActionPerformed

    private void modelpctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelpctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelpctxtActionPerformed

    private void procesadorpctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesadorpctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procesadorpctxtActionPerformed

    private void marcapctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcapctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcapctxtActionPerformed

    private void rampctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rampctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rampctxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaComputadores().setVisible(true);
            }
        });

    }

    public vistaComputadores(JButton cerrarbtn, JTextField discopctxt, JLabel jLabel1, JLabel jLabel2, JLabel jLabel3, JLabel jLabel4, JLabel jLabel5, JLabel jLabel8, JTextField marcapctxt, JTextField modelpctxt, JTextField procesadorpctxt, JTextField rampctxt, JButton regresarbtn, JButton reparacioncbtn, JButton reparacionpbtn, JTextField totalpctxt) {
        this.cerrarbtn = cerrarbtn;
        this.discopctxt = discopctxt;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jLabel8 = jLabel8;
        this.marcapctxt = marcapctxt;
        this.modelpctxt = modelpctxt;
        this.procesadorpctxt = procesadorpctxt;
        this.rampctxt = rampctxt;
        this.regresarbtn = regresarbtn;
        this.reparacioncbtn = reparacioncbtn;
        this.reparacionpbtn = reparacionpbtn;
        this.totalpctxt = totalpctxt;
    }

    public JButton getCerrarbtn() {
        return cerrarbtn;
    }

    public void setCerrarbtn(JButton cerrarbtn) {
        this.cerrarbtn = cerrarbtn;
    }

    public JTextField getDiscopctxt() {
        return discopctxt;
    }

    public void setDiscopctxt(JTextField discopctxt) {
        this.discopctxt = discopctxt;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JTextField getMarcapctxt() {
        return marcapctxt;
    }

    public void setMarcapctxt(JTextField marcapctxt) {
        this.marcapctxt = marcapctxt;
    }

    public JTextField getModelpctxt() {
        return modelpctxt;
    }

    public void setModelpctxt(JTextField modelpctxt) {
        this.modelpctxt = modelpctxt;
    }

    public JTextField getProcesadorpctxt() {
        return procesadorpctxt;
    }

    public void setProcesadorpctxt(JTextField procesadorpctxt) {
        this.procesadorpctxt = procesadorpctxt;
    }

    public JTextField getRampctxt() {
        return rampctxt;
    }

    public void setRampctxt(JTextField rampctxt) {
        this.rampctxt = rampctxt;
    }

    public JButton getRegresarbtn() {
        return regresarbtn;
    }

    public void setRegresarbtn(JButton regresarbtn) {
        this.regresarbtn = regresarbtn;
    }

    public JButton getReparacioncbtn() {
        return reparacioncbtn;
    }

    public void setReparacioncbtn(JButton reparacioncbtn) {
        this.reparacioncbtn = reparacioncbtn;
    }

    public JButton getReparacionpbtn() {
        return reparacionpbtn;
    }

    public void setReparacionpbtn(JButton reparacionpbtn) {
        this.reparacionpbtn = reparacionpbtn;
    }

    public JTextField getTotalpctxt() {
        return totalpctxt;
    }

    public void setTotalpctxt(JTextField totalpctxt) {
        this.totalpctxt = totalpctxt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JLabel jLabel4;
    private JTextField discopctxt;
    private JTextField totalpctxt;
    private JLabel jLabel5;
    private JButton regresarbtn;
    private JButton cerrarbtn;
    private JButton reparacionpbtn;
    private JTextField modelpctxt;
    private JTextField procesadorpctxt;
    private JButton reparacioncbtn;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField marcapctxt;
    private JLabel jLabel8;
    private JLabel jLabel3;
    private JTextField rampctxt;
    // End of variables declaration//GEN-END:variables
}
