/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author Rain
 */
public class vistaTelevisores extends javax.swing.JFrame {

    /**
     * Creates new form vistaTelevisores
     */
    public vistaTelevisores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jLabel4 = new JLabel();
        tamatvtxt = new JTextField();
        totaltvtxt = new JTextField();
        jLabel5 = new JLabel();
        regresarbtn = new JButton();
        cerrarbtn = new JButton();
        reparacionpbtn = new JButton();
        modeltvtxt = new JTextField();
        reparacioncbtn = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        marcatvtxt = new JTextField();
        jLabel8 = new JLabel();
        tecnologiatvtxt = new JTextField();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //---- jLabel4 ----
        jLabel4.setText("Marca");

        //---- tamatvtxt ----
        tamatvtxt.addActionListener(e -> tamatvtxtActionPerformed(e));

        //---- totaltvtxt ----
        totaltvtxt.addActionListener(e -> totaltvtxtActionPerformed(e));

        //---- jLabel5 ----
        jLabel5.setText("Tama\u00f1o");

        //---- regresarbtn ----
        regresarbtn.setText("Regresar");

        //---- cerrarbtn ----
        cerrarbtn.setText("Cerrar");

        //---- reparacionpbtn ----
        reparacionpbtn.setText("Reparacion Preventiva");
        reparacionpbtn.addActionListener(e -> reparacionpbtnActionPerformed(e));

        //---- modeltvtxt ----
        modeltvtxt.addActionListener(e -> modeltvtxtActionPerformed(e));

        //---- reparacioncbtn ----
        reparacioncbtn.setText("Reparacion Correctiva");

        //---- jLabel1 ----
        jLabel1.setText("Modelo");

        //---- jLabel2 ----
        jLabel2.setText("Tecnologia");

        //---- marcatvtxt ----
        marcatvtxt.addActionListener(e -> marcatvtxtActionPerformed(e));

        //---- jLabel8 ----
        jLabel8.setText("Total");

        //---- tecnologiatvtxt ----
        tecnologiatvtxt.addActionListener(e -> tecnologiatvtxtActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGap(100, 100, 100)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addComponent(marcatvtxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addComponent(modeltvtxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addComponent(tecnologiatvtxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addComponent(tamatvtxt, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(64, 64, 64))
                                        .addComponent(totaltvtxt, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap(110, Short.MAX_VALUE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(regresarbtn)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cerrarbtn))
                                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                    .addComponent(reparacioncbtn)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reparacionpbtn)))
                            .addGap(30, 30, 30))))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel4))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(marcatvtxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(modeltvtxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(tecnologiatvtxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(tamatvtxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(10, 10, 10)
                            .addComponent(totaltvtxt, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGap(32, 32, 32)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(reparacionpbtn)
                        .addComponent(reparacioncbtn))
                    .addGap(26, 26, 26)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(cerrarbtn)
                        .addComponent(regresarbtn))
                    .addContainerGap(35, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void tamatvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamatvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamatvtxtActionPerformed

    private void totaltvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltvtxtActionPerformed

    private void reparacionpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reparacionpbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reparacionpbtnActionPerformed

    private void modeltvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeltvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeltvtxtActionPerformed

    private void marcatvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcatvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcatvtxtActionPerformed

    private void tecnologiatvtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecnologiatvtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecnologiatvtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaTelevisores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaTelevisores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaTelevisores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaTelevisores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaTelevisores().setVisible(true);
            }
        });

    }

    public vistaTelevisores(JButton cerrarbtn, JLabel jLabel1, JLabel jLabel2, JLabel jLabel4, JLabel jLabel5, JLabel jLabel8, JTextField marcatvtxt, JTextField modeltvtxt, JButton regresarbtn, JButton reparacioncbtn, JButton reparacionpbtn, JTextField tamatvtxt, JTextField tecnologiatvtxt, JTextField totaltvtxt) {
        this.cerrarbtn = cerrarbtn;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel4 = jLabel4;
        this.jLabel5 = jLabel5;
        this.jLabel8 = jLabel8;
        this.marcatvtxt = marcatvtxt;
        this.modeltvtxt = modeltvtxt;
        this.regresarbtn = regresarbtn;
        this.reparacioncbtn = reparacioncbtn;
        this.reparacionpbtn = reparacionpbtn;
        this.tamatvtxt = tamatvtxt;
        this.tecnologiatvtxt = tecnologiatvtxt;
        this.totaltvtxt = totaltvtxt;
    }

    public JButton getCerrarbtn() {
        return cerrarbtn;
    }

    public void setCerrarbtn(JButton cerrarbtn) {
        this.cerrarbtn = cerrarbtn;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JTextField getMarcatvtxt() {
        return marcatvtxt;
    }

    public void setMarcatvtxt(JTextField marcatvtxt) {
        this.marcatvtxt = marcatvtxt;
    }

    public JTextField getModeltvtxt() {
        return modeltvtxt;
    }

    public void setModeltvtxt(JTextField modeltvtxt) {
        this.modeltvtxt = modeltvtxt;
    }

    public JButton getRegresarbtn() {
        return regresarbtn;
    }

    public void setRegresarbtn(JButton regresarbtn) {
        this.regresarbtn = regresarbtn;
    }

    public JButton getReparacioncbtn() {
        return reparacioncbtn;
    }

    public void setReparacioncbtn(JButton reparacioncbtn) {
        this.reparacioncbtn = reparacioncbtn;
    }

    public JButton getReparacionpbtn() {
        return reparacionpbtn;
    }

    public void setReparacionpbtn(JButton reparacionpbtn) {
        this.reparacionpbtn = reparacionpbtn;
    }

    public JTextField getTamatvtxt() {
        return tamatvtxt;
    }

    public void setTamatvtxt(JTextField tamatvtxt) {
        this.tamatvtxt = tamatvtxt;
    }

    public JTextField getTecnologiatvtxt() {
        return tecnologiatvtxt;
    }

    public void setTecnologiatvtxt(JTextField tecnologiatvtxt) {
        this.tecnologiatvtxt = tecnologiatvtxt;
    }

    public JTextField getTotaltvtxt() {
        return totaltvtxt;
    }

    public void setTotaltvtxt(JTextField totaltvtxt) {
        this.totaltvtxt = totaltvtxt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JLabel jLabel4;
    private JTextField tamatvtxt;
    private JTextField totaltvtxt;
    private JLabel jLabel5;
    private JButton regresarbtn;
    private JButton cerrarbtn;
    private JButton reparacionpbtn;
    private JTextField modeltvtxt;
    private JButton reparacioncbtn;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JTextField marcatvtxt;
    private JLabel jLabel8;
    private JTextField tecnologiatvtxt;
    // End of variables declaration//GEN-END:variables
}
